apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: e13f7bc3-1509-4990-99e2-76970ae3b0a8
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/reroute-training/cloud-run-source-deploy/reroute-app
    run.googleapis.com/build-name: projects/828281382646/locations/us-central1/builds/e13f7bc3-1509-4990-99e2-76970ae3b0a8
    run.googleapis.com/build-source-location: gs://run-sources-reroute-training-us-central1/services/reroute-app/1753302075.567121-41697bae2a4145f48c19190ae02b42fc.zip#1753302088917367
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://reroute-app-828281382646.us-central1.run.app","https://reroute-app-33fih5yanq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: reroute-app
  namespace: '828281382646'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 531.0.0
        run.googleapis.com/cloudsql-instances: reroute-training:us-central1:reroute-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: kkkvoywbfk
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: SECRET_KEY
        - name: STRAVA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: STRAVA_CLIENT_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: OPENAI_API_KEY
        image: gcr.io/reroute-training/reroute-app:latest
        ports:
        - containerPort: 8000
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8000
          timeoutSeconds: 240
      serviceAccountName: 828281382646-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
