"""add_user_sessions_table

Revision ID: bb8513bebcd9
Revises: 1c15fd6e1355
Create Date: 2025-07-19 09:18:00.243290

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb8513bebcd9"
down_revision: Union[str, None] = "1c15fd6e1355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_sessions table
    op.create_table(
        "user_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_index(
        op.f("ix_user_sessions_session_token"),
        "user_sessions",
        ["session_token"],
        unique=False,
    )

    # Update users table constraints
    try:
        op.drop_constraint("profiles_id_fkey", "profiles", type_="foreignkey")
        op.create_foreign_key(None, "profiles", "users", ["id"], ["id"])
    except:
        pass

    try:
        op.drop_index("ix_users_email", table_name="users")
        op.create_unique_constraint(None, "users", ["email"])
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_sessions table
    op.drop_index(op.f("ix_user_sessions_session_token"), table_name="user_sessions")
    op.drop_table("user_sessions")

    # Revert users table constraints
    try:
        op.drop_constraint(None, "users", type_="unique")
        op.create_index("ix_users_email", "users", ["email"], unique=False)
    except:
        pass

    try:
        op.drop_constraint(None, "profiles", type_="foreignkey")
        op.create_foreign_key(
            "profiles_id_fkey", "profiles", "users", ["id"], ["id"], ondelete="CASCADE"
        )
    except:
        pass
    # ### end Alembic commands ###
